;----------------------------------------------------------------------------
pal_table_bg_fade_0:
.db             %00000000 ;  0: Black
.db             %00000000 ;  1: Gray 1
.db             %00000000 ;  2: Gray 2
.db             %00000000 ;  3: White
.db             %00000000 ;  4: Light Blue
;----------------------------------------------------------------------------
pal_table_bg_fade_1:
.db             %00000000 ;  0: Black
.db             %00000000 ;  1: Gray 1
.db             %00000000 ;  2: Gray 2
.db             %00010101 ;  3: White
.db             %00010000 ;  4: Light Blue
;----------------------------------------------------------------------------
pal_table_bg_fade_2:
.db             %00000000 ;  0: Black
.db             %00000000 ;  1: Gray 1
.db             %00010101 ;  2: Gray 2
.db             %00101010 ;  3: White
.db             %00100000 ;  4: Light Blue
;----------------------------------------------------------------------------
pal_table_bg:
.db             %00000000 ;  0: Black
.db             %00010101 ;  1: Gray 1
.db             %00101010 ;  2: Gray 2
.db             %00111111 ;  3: White
.db             %00110000 ;  4: Light Blue
;----------------------------------------------------------------------------
pal_table_fg:
.db             %00000000 ;  0: <UNUSED>
.db             %00000000 ;  1: Black
.db             %00000110 ;  2: Marron
.db             %00000111 ;  3: Light Orange
.db             %00011011 ;  4: Peach
.db             %00001111 ;  5: Yellow
.db             %00011001 ;  6: Green (background)
.db             %00111111 ;  7: White
.db             %00000000 ;  8: <UNUSED>
.db             %00000000 ;  9: <UNUSED>
.db             %00000000 ; 10: <UNUSED>
.db             %00000000 ; 11: <UNUSED>
.db             %00000000 ; 12: <UNUSED>
.db             %00000000 ; 13: <UNUSED>
.db             %00000000 ; 14: <UNUSED>
.db             %00000000 ; 15: <UNUSED>
;----------------------------------------------------------------------------
pal_table_mode2:
.db             %00000000 ;  0: Transparent=Black
.db             %00000000 ;  1: Black
.db             %00001100 ;  2: Medium green
.db             %00011101 ;  3: Light green
.db             %00010000 ;  4: Dark blue
.db             %00110000 ;  5: light blue
.db             %00000001 ;  6: Dark Red
.db             %00111100 ;  7: Cyan
.db             %00000011 ;  8: Medium Red
.db             %00010111 ;  9: light red
.db             %00001010 ; 10: dark yellow
.db             %00001111 ; 11: light yellow
.db             %00001000 ; 12: dark green
.db             %00110011 ; 13: magenta
.db             %00101010 ; 14: grey
.db             %00111111 ; 15: white

